### ISSUE TITLE
Many CPANTesters fails

### ISSUE THREAD

**Issue by StarLightPL** [holophrastic/password-policy#1]
Hello,

I'm looking at this module as a part of CPAN Pull Request challenge, and I have noticed that a majority of CPANTesters fails is due to the fact that testbeds cannot load sample.yml file. This is due to missing dependency for YAML while testing. If you would be so kind and add CPAN's Meta files to this repo, I'd try to fix those.

tia,
StarLightPL

**Comment by holophrastic** [comment]
Sure. I haven't touched this thing in a very long time (it still works for the thing I wrote it for), but I'll clean it up this weekend. What all would you like me to add?

**Comment by StarLightPL** [comment]
The thing with #cpanpr is me doing the cleaning for you ;-) I'd like to edit the Makefile.pl (as Meta.yml & Meta.json are generated) to make sure testbeds include YAML. Basically files which are in the root dir of the distribution: https://metacpan.org/source/ANELSON/Password-Policy-0.02
I could also copied these files from CPAN but I wanted to ask you first :)

I also want to do some minor changes to tests (like adding plans instead of done_testing), and investigate one failing (on win32) test if I can reproduce it.

**Comment by holophrastic** [comment]
Oh, of course. Submit a PR and I'll get it out to CPAN shortly. Thanks much.

**Comment by StarLightPL** [comment]
no prob. Will try to do it over the weekend, this issue can be closed then.
