### ISSUE TITLE
utf-8 passwords

### ISSUE THREAD

**Issue by openstrike** [holophrastic/password-policy#3]
Hello,

I've hit a problem when using utf-8 passwords and hope you can clarify.

Passing unencoded/decoded utf-8 passwords to the process() method fails the length rule as the length is computed to be 0, regardless of the actual length. In order to have the length computed correctly we need to encode the password string as bytes and then pass that to process() instead. Reading the [source code to Password::Policy::Rule::Length](https://metacpan.org/release/ANELSON/Password-Policy-0.04/source/lib/Password/Policy/Rule/Length.pm) this seems to have been done on purpose. However, when the password is encoded this way other problems arise.

Before I go too far down this rabbit hole, please could you confirm that Password::Policy expects a utf-8 password to be encoded before calling process()?

Thanks very much.

**Comment by holophrastic** [comment]
That sounds right, but I haven't touched this in a _very_ long time; I'll get a development environment running for it tonight and confirm that things are working like they should (and see if I can reproduce the issue you're having)

**Comment by openstrike** [comment]
Thanks. Here's my very simple test script. Test 2 is the one which fails.

```
use strict;
use warnings;
use utf8;

use Test::More tests => 4;
use Test::Fatal 'lives_ok';

use Password::Policy::Rule::Length;
use Encode 'encode';

my $pw = 'οМΛʊώȯŨͲĔʨҚҠԾǔǶՍŎѢʯΝ';
my $len = length $pw;
my $rule = Password::Policy::Rule::Length->new (10);
is $len, 20, 'Standard len is correct';
lives_ok { $rule->check ($pw) } '20-char *decoded* pw is long enough';

my $encpw = encode ('UTF-8', $pw, Encode::FB_CROAK);
my $strmb = String::Multibyte->new ('UTF8');
my $mblen = $strmb->length ($encpw);
is $mblen, 20, 'Multibyte len is correct';
is $rule->check ($encpw), 1, '20-char *encoded* pw is long enough';
```

**Comment by holophrastic** [comment]
I've added your test to the suite and added a PR that makes it pass: https://github.com/holophrastic/password-policy/pull/4

tl,dr: String::Multibyte has a method (`islegal`) to see if it's going to give a proper response to a given string; I use it now to see if I can use String::Multibyte or if I have to fall back to `length`. Let me know if this works for you, and if so I'll put out a release.

**Comment by openstrike** [comment]
Thanks for coming up with this so quickly!

The modification does work and the length rule now passes, which is great.

However, this brings me back to the rabbit hole mentioned above which I will need to dig through. That is starting to look like an unrelated issue though so I think this improvement is fine for a release as it stands.

**Comment by holophrastic** [comment]
0.06 has been uploaded to PAUSE - took me a minute to remember how to do that. Let me know if you need anything else, and thanks for using Password::Policy! I wrote it for a one-off client so, so long ago, but decided it was worth cleaning up and open sourcing, so I'm glad someone else is getting some use out of it!

**Comment by openstrike** [comment]
Thanks - this is all working well now. My dependent module ([Password::Policy::Rule::Pwned](https://metacpan.org/pod/Password::Policy::Rule::Pwned)) has also been amended to handle encoded and decoded passwords in version 0.03.
